[package]
name = "nop-macros"
description = "Procedural macros to do nothing, allowing attributes to be used as metadata"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Techcable/nop-macros.rust"
readme = "README.md"

[lib]
proc-macro = true
